version: 2.1

jobs:
  build-and-test:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Install GCC and Python-dev
          command: |
            apt-get update
            apt-get install -y gcc python3-dev
      - run:
          name: Install and upgrade pip, setuptools, and virtualenv
          command: pip install -U pip setuptools virtualenv
      - run:
          name: Install conda environment
          command: conda env create -f environment.yml
      - run:
          name: Run unit tests
          command: |
            source activate tree_embedding
            python -m unittest discover tests -v

workflows:
  main:
    jobs:
      - build-and-test
