hydra:
  run:
    dir: .
  output_subdir: null
  job_logging: null
  hydra_logging: null

num_workers: 1
seed: 7
log_offline: true

# ===== Resuming =====
resume_checkpoint: null

# ===== Data =====
data_folder: ../data
dataset: java-test-asts

max_labels: null
max_label_parts: 5
max_tokens: null
max_token_parts: 5


# ===== Hyperparameters =====
learning_rate: 0.01
weight_decay: 0
lr_decay_gamma: 0.95

batch_size: 10
n_epochs: 3000

patience: 10
clip_norm: 5
teacher_forcing: 0.5

# ===== Training parameters =====
val_every_epoch: 1
save_every_epoch: 1
log_every_step: 10
progress_bar_refresh_rate: 10


# ===== Model parameters =====
embedding_size: 10
encoder_dropout: 0.5
encoder_size: 10
decoder_size: 10
decoder_num_layers: 1
rnn_dropout: 0.25
