hydra:
  run:
    dir: .

num_workers: 10

# ===== Data =====
data_folder: ../data
dataset: java-test-asts

max_labels: null
max_label_parts: 5
max_tokens: null
max_token_parts: 5


# ===== Hyperparameters =====
batch_size: 10
